openapi: 3.1.0
info:
  title: Catalog Management API
  description: API for managing catalog entries in library systems, allowing librarians to manage catalog entries and tag books for recommendations
  version: 1.0.0
  contact:
    name: Annegret Junker
  x-api-id: 7a2c8f1d-9e4b-4a33-bc12-947d6fae3087
  x-audience: external-public

servers:
  - url: 'https://apis.online-library.org/catalog-management'
    description: Production server

security:
  - openIdConnect:
      - catalog:read
      - catalog:write
      - catalog:admin

tags:
  - name: Catalog Entries
    description: Catalog entry management operations
  - name: Abstracts
    description: Abstract management for catalog entries
  - name: Tags
    description: Tag management for catalog entries

paths:
  /catalog-entries:
    get:
      description: Get a list of catalog entries with optional filtering
      operationId: getCatalogEntries
      summary: Retrieve catalog entries
      tags:
        - Catalog Entries
      security:
        - openIdConnect:
            - catalog:read
      parameters:
        - $ref: '#/components/parameters/SearchParameter'
        - $ref: '#/components/parameters/VersionParameter'
        - $ref: '#/components/parameters/AuthorsSearchParameter'
        - $ref: '#/components/parameters/IsbnSearchParameter'
        - $ref: '#/components/parameters/PublisherSearchParameter'
        - $ref: '#/components/parameters/TagsSearchParameter'
        - $ref: '#/components/parameters/PageSizeSearchParameter'
        - $ref: '#/components/parameters/OffsetSearchParameter'
      responses:
        '200':
          $ref: '#/components/responses/CatalogEntriesResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '500':
          $ref: '#/components/responses/ServiceNotAvailableResponse'

    post:
      description: Create a new catalog entry. New entries can be also added automatically by 'BookPurchased' event.
      operationId: createCatalogEntry
      summary: Create new catalog entry
      tags:
        - Catalog Entries
      security:
        - openIdConnect:
            - catalog:write
      parameters:
        - $ref: '#/components/parameters/VersionParameter'
      requestBody:
        $ref: '#/components/requestBodies/CatalogEntryCreateRequest'
      responses:
        '201':
          $ref: '#/components/responses/CatalogEntryCreatedResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '500':
          $ref: '#/components/responses/ServiceNotAvailableResponse'

  /catalog-entries/{catalog-entry}:
    get:
      description: Retrieve a specific catalog entry by its identifier
      operationId: getCatalogEntryById
      summary: Get catalog entry by ID
      tags:
        - Catalog Entries
      security:
        - openIdConnect:
            - catalog:read
      parameters:
        - $ref: '#/components/parameters/CatalogEntryIdParameter'
        - $ref: '#/components/parameters/VersionParameter'
      responses:
        '200':
          $ref: '#/components/responses/CatalogEntryResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/ServiceNotAvailableResponse'

    put:
      description: Update an existing catalog entry. Only librarians can change entries.
      operationId: updateCatalogEntry
      summary: Update catalog entry
      tags:
        - Catalog Entries
      security:
        - openIdConnect:
            - catalog:write
      parameters:
        - $ref: '#/components/parameters/CatalogEntryIdParameter'
        - $ref: '#/components/parameters/VersionParameter'
      requestBody:
        $ref: '#/components/requestBodies/CatalogEntryUpdateRequest'
      responses:
        '200':
          $ref: '#/components/responses/CatalogEntryLinkResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/ServiceNotAvailableResponse'

    delete:
      operationId: deleteCatalogEntry
      summary: Delete catalog entry
      description: Delete a catalog entry from the catalog
      tags:
        - Catalog Entries
      security:
        - openIdConnect:
            - catalog:admin
      parameters:
        - $ref: '#/components/parameters/CatalogEntryIdParameter'
        - $ref: '#/components/parameters/VersionParameter'
      responses:
        '204':
          description: Catalog entry deleted successfully
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/ServiceNotAvailableResponse'

  /catalog-entries/{catalog-entry}/abstracts:
    put:
      description: Update or add an abstract to a catalog entry
      operationId: updateCatalogEntryAbstract
      summary: Update catalog entry abstract
      tags:
        - Abstracts
      security:
        - openIdConnect:
            - catalog:write
      parameters:
        - $ref: '#/components/parameters/CatalogEntryIdParameter'
        - $ref: '#/components/parameters/VersionParameter'
      requestBody:
        $ref: '#/components/requestBodies/AbstractUpdateRequest'
      responses:
        '200':
          $ref: '#/components/responses/AbstractResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/ServiceNotAvailableResponse'

  /catalog-entries/{catalog-entry}/tags:
    put:
      description: Update tags for a catalog entry to enable book recommendations
      operationId: updateCatalogEntryTags
      summary: Update catalog entry tags
      tags:
        - Tags
      security:
        - openIdConnect:
            - catalog:write
      parameters:
        - $ref: '#/components/parameters/CatalogEntryIdParameter'
        - $ref: '#/components/parameters/VersionParameter'
      requestBody:
        $ref: '#/components/requestBodies/TagsUpdateRequest'
      responses:
        '200':
          $ref: '#/components/responses/TagsResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/ServiceNotAvailableResponse'

components:
  parameters:
    CatalogEntryIdParameter:
      description: Unique identifier for the catalog entry
      name: catalog-entry
      in: path
      required: true
      schema:
        type: string
        format: uuid
        examples:
          - b2c3f638-d8c1-4c36-8f6b-b51041a102fc

    SearchParameter:
      description: Search term for catalog entries
      name: search
      in: query
      required: false
      schema:
        type: string
        maxLength: 100
        examples:
          - Domain-Driven Design

    AuthorsSearchParameter:
      description: Filter by author names
      name: authors
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
          minLength: 2
          maxLength: 40
          examples:
            - Eric Evans

    PublisherSearchParameter:
      description: Filter by publisher
      name: publisher
      in: query
      required: false
      schema:
        type: string
        minLength: 2
        maxLength: 40
        examples:
          - Addison Wesley

    IsbnSearchParameter:
      description: Filter by ISBN
      name: isbn
      in: query
      required: false
      schema:
        type: string
        pattern: (ISBN(?:[- ]*1[03])?:* )+?((?=[0-9X]{10}$|(?=(?:[0-9]+[- ]){3})[- 0-9X]{13}|97[89][0-9]{10}|(?=(?:[0-9]+[- ]){4})[- 0-9]{17})(?:97[89][- ]?)?[0-9]{1,5}[- ]?[0-9]+[- ]?[0-9]+[- ]?[0-9X])
        examples:
          - 0-321-12521-5
          - 979-8-8688-1456-3
          - 978-93-65892-529

    TagsSearchParameter:
      description: Filter by tags
      name: tags
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
          minLength: 2
          maxLength: 20
          examples:
            - DDD

    PageSizeSearchParameter:
      description: Maximum number of entries to return
      name: limit
      in: query
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 100
        default: 20
        examples:
          - 20

    OffsetSearchParameter:
      description: Number of entries to skip
      name: offset
      in: query
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 0
        examples:
          - 20

    VersionParameter:
      name: version
      in: header
      required: true
      description: API version
      schema:
        type: string
        default: 1.0.0
        enum:
          - 1.0.0
        examples:
          - 1.0.0

  requestBodies:
    CatalogEntryCreateRequest:
      description: Catalog entry creation request
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CatalogEntryCreate'

    CatalogEntryUpdateRequest:
      description: Catalog entry update request
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CatalogEntryUpdate'

    AbstractUpdateRequest:
      description: Abstract update request
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Abstract'

    TagsUpdateRequest:
      description: Tags update request
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Tags'

  responses:
    CatalogEntryResponse:
      description: Response with a single catalog entry
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CatalogEntry'

    CatalogEntryLinkResponse:
      description: Link to a single entry of the catalog
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CatalogEntryLink'

    CatalogEntriesResponse:
      description: List of catalog entries
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CatalogEntriesWithPagination'

    CatalogEntryCreatedResponse:
      description: Catalog entry created successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CatalogEntryLink'

    AbstractResponse:
      description: Response with an abstract of a catalog entry
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Abstract'

    TagsResponse:
      description: Tags updated successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Tags'

    BadRequestResponse:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFoundResponse:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    ForbiddenResponse:
      description: Access forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    ServiceNotAvailableResponse:
      description: Service unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    CatalogEntry:
      type: object
      required:
        - id
        - title
        - authors
        - isbn
        - publisher
        - publishedOn
        - createdAt
        - updatedAt
      allOf:
        - $ref: '#/components/schemas/CatalogEntryCreate'
        - properties:
            id:
              description: Unique identifier for the catalog entry
              type: string
              format: uuid
              examples:
                - b2c3f638-d8c1-4c36-8f6b-b51041a102fc
            createdAt:
              type: string
              format: date-time
              description: Timestamp when the entry was created
              readOnly: true
            updatedAt:
              type: string
              format: date-time
              description: Timestamp when the entry was last updated
              readOnly: true

    CatalogEntryCreate:
      type: object
      required:
        - title
        - authors
        - isbn
        - publisher
        - publishedOn
      properties:
        title:
          description: Title of the book or publication
          type: string
          minLength: 1
          maxLength: 500
          examples:
            - Domain-Driven Design
        authors:
          description: Authors of the publication (at least one required)
          type: array
          minItems: 1
          maxItems: 10
          items:
            type: string
            minLength: 1
            maxLength: 200
            examples:
              - Eric Evans
        isbn:
          description: ISBN of the publication
          type: string
          pattern: '^(?:ISBN(?:-1[03])?:? )?(?=[0-9X]{10}$|(?=(?:[0-9]+[- ]){3})[- 0-9X]{13}$|97[89][0-9]{10}$|(?=(?:[0-9]+[- ]){4})[- 0-9]{17}$)(?:97[89][- ]?)?[0-9]{1,5}[- ]?[0-9]+[- ]?[0-9]+[- ]?[0-9X]$'
          examples:
            - 0-321-12521-5
            - 979-8-8688-1456-3
            - 978-93-65892-529
        publisher:
          description: Publisher of the publication
          type: string
          minLength: 1
          maxLength: 200
          examples:
            - Addison Wesley
        publishedOn:
          description: Publication date
          type: string
          format: date
          examples:
            - 2004-01-01
        abstract:
          $ref: '#/components/schemas/Abstract'
        tags:
          description: Tags for categorization and recommendations
          type: array
          minItems: 0
          maxItems: 20
          items:
            type: string
            minLength: 2
            maxLength: 50
            examples:
              - DDD

    CatalogEntryUpdate:
      description: Properties to update a catalog entry
      type: object
      properties:
        title:
          description: Title of the book or publication
          type: string
          minLength: 1
          maxLength: 500
          examples:
            - Domain-Driven Design
        authors:
          description: Authors of the publication (at least one required)
          type: array
          minItems: 1
          maxItems: 10
          items:
            type: string
            minLength: 1
            maxLength: 200
            examples:
              - Eric Evans
        isbn:
          description: ISBN of the publication
          type: string
          pattern: '^(?:ISBN(?:-1[03])?:? )?(?=[0-9X]{10}$|(?=(?:[0-9]+[- ]){3})[- 0-9X]{13}$|97[89][0-9]{10}$|(?=(?:[0-9]+[- ]){4})[- 0-9]{17}$)(?:97[89][- ]?)?[0-9]{1,5}[- ]?[0-9]+[- ]?[0-9]+[- ]?[0-9X]$'
          examples:
            - 0-321-12521-5
            - 979-8-8688-1456-3
            - 978-93-65892-529
        publisher:
          description: Publisher of the publication
          type: string
          minLength: 1
          maxLength: 200
          examples:
            - Addison Wesley
        publishedOn:
          description: Publication date
          type: string
          format: date
          examples:
            - 2004-01-01

    CatalogEntryLink:
      description: Link to a specific catalog entry
      type: object
      required:
        - link
      properties:
        objectType:
          description: Simple type of an object
          type: string
          minLength: 5
          maxLength: 80
          default: object
          examples:
            - CatalogEntry
        link:
          description: Link to the object
          type: string
          format: uri
          examples:
            - https://apis.online-library.org/catalog-management/catalog-entries/b2c3f638-d8c1-4c36-8f6b-b51041a102fc

    CatalogEntriesWithPagination:
      description: Collection of catalog entries with pagination information
      type: object
      required:
        - catalogEntries
        - pagination
      properties:
        catalogEntries:
          description: Collection of catalog entries
          type: array
          minItems: 1
          maxItems: 100
          items:
            $ref: '#/components/schemas/CatalogEntry'
        pagination:
          $ref: '#/components/schemas/Pagination'

    Pagination:
      description: Information of pagination application of a collection
      type: object
      required:
        - limit
        - offset
        - total
      properties:
        limit:
          description: Size of a page - limit of entries of a page
          type: integer
          format: int32
          minimum: 1
          maximum: 100
          default: 20
          examples:
            - 20
        offset:
          description: Number of entries which are skipped before the current page
          type: integer
          format: int32
          minimum: 0
          default: 0
          examples:
            - 10
        total:
          description: Total number of entries of the collection
          type: integer
          format: int32
          minimum: 1
          examples:
            - 132

    Abstract:
      type: object
      required:
        - content
      properties:
        content:
          type: string
          minLength: 1
          maxLength: 2000
          description: Abstract or summary content

    Tag:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 50
          description: Tag name for categorization

    Tags:
      description: Collection of tag names for categorization
      required:
        - tags
      properties:
        tags:
          type: array
          minItems: 0
          maxItems: 20
          items:
            $ref: '#/components/schemas/Tag'

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          description: Additional error details




  securitySchemes:
    openIdConnect:
      type: openIdConnect
      openIdConnectUrl: https://auth.online-library.org/.well-known/openid-configuration
  
