openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
  description: API for managing tasks, attachments, and notes in a task management system.

servers:
  - url: http://api.example.com/v1

paths:
  /tasks:
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Task created successfully
        '400':
          description: Invalid input

    get:
      summary: Retrieve a list of tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    status:
                      type: string

  /tasks/{taskId}:
    parameters:
      - name: taskId
        in: path
        required: true
        schema:
          type: integer

    get:
      summary: Retrieve details of a specific task
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
                  status:
                    type: string

    put:
      summary: Update a specific task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                status:
                  type: string
      responses:
        '200':
          description: Task updated successfully

  /tasks/{taskId}/attachments:
    post:
      summary: Add an attachment to a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fileName:
                  type: string
                fileData:
                  type: string
                  format: binary
      responses:
        '201':
          description: Attachment added successfully

  /tasks/{taskId}/notes:
    post:
      summary: Add a note to a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                note:
                  type: string
      responses:
        '201':
          description: Note added successfully

  /tasks/{taskId}/follow-ups:
    post:
      summary: Create a follow-up for a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                followUpDate:
                  type: string
                  format: date
                notes:
                  type: string
      responses:
        '201':
          description: Follow-up created successfully
  
