openapi: 3.0.0
info:
  title: Task Management API
  version: 1.0.0
  description: API for managing tasks, notes, documents, and attachments.

paths:
  /tasks:
    get:
      summary: Get a list of tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Task created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /tasks/{taskId}:
    parameters:
      - in: path
        name: taskId
        required: true
        description: ID of the task
        schema:
          type: string

    put:
      summary: Update a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: Task updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

    delete:
      summary: Delete a task
      responses:
        '204':
          description: Task deleted

  /tasks/{taskId}/notes:
    post:
      summary: Add a note to a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      responses:
        '201':
          description: Note added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
        description:
          type: string
          nullable: true
        status:
          type: string
          enum: [New, In Progress, Done, Declined]
        assignee:
          $ref: '#/components/schemas/TeamMember'
        creator:
          $ref: '#/components/schemas/TeamMember'
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
        notes:
          type: array
          items:
            $ref: '#/components/schemas/Note'

    Note:
      type: object
      properties:
        id:
          type: string
        text:
          type: string
        author:
          $ref: '#/components/schemas/TeamMember'
        created_at:
          type: string
          format: date-time

    Attachment:
      type: object
      properties:
        id:
          type: string
        filename:
          type: string
        document:
          $ref: '#/components/schemas/Document'

    Document:
      type: object
      properties:
        id:
          type: string
        files:
          type: array
          items:
            $ref: '#/components/schemas/File'

    File:
      type: object
      properties:
        id:
          type: string
        name:
          type: string

    TeamMember:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
  
