openapi: 3.1.0
info:
  title: Task Management API
  description: |
    Task Management API to be used by team members and clerks.
    Users can create, update, and manage tasks with different statuses.
    Tasks can be assigned to employees and tracked through various states.
  contact:
    email: team.taskmanagement@our-company.com
    name: Team Task Management
    url: https://api.our-company.com/task-management
  version: 1.0.0
  x-api-id: a1b2c3d4-e5f6-7g8h-9i0j-k1l2m3n4o5p6
  x-audience: external-public
servers:
  - url: 'https://api.our-company.com/task-management/'
security:
  - openIdConnect:
      - task:read
      - task:write
      - task:admin
tags:
  - name: Tasks
    description: All endpoints to manage tasks
  - name: Task Status
    description: All endpoints to manage task status
  - name: Task Assignment
    description: All endpoints to manage task assignments
paths:
  /tasks:
    get:
      description: Retrieves a list of all tasks
      operationId: getAllTasks
      tags:
        - Tasks
      security:
        - openIdConnect:
            - task:read
      parameters:
        - $ref: '#/components/parameters/VersionParameter'
        - name: status
          in: query
          description: Filter tasks by status
          required: false
          schema:
            $ref: '#/components/schemas/TaskStatus'
        - name: assignee
          in: query
          description: Filter tasks by assignee employee ID
          required: false
          schema:
            type: string
            format: uuid
      responses:
        '200':
          $ref: '#/components/responses/TaskListResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '500':
          $ref: '#/components/responses/ServiceNotAvailableResponse'
        default:
          $ref: '#/components/responses/DefaultResponse'

    post:
      description: Creates a new task
      operationId: createNewTask
      tags:
        - Tasks
      security:
        - openIdConnect:
            - task:write
      parameters:
        - $ref: '#/components/parameters/VersionParameter'
      requestBody:
        $ref: '#/components/requestBodies/TaskCreationRequest'
      responses:
        '201':
          $ref: '#/components/responses/LinkToTaskResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '500':
          $ref: '#/components/responses/ServiceNotAvailableResponse'
        default:
          $ref: '#/components/responses/DefaultResponse'

  /tasks/{taskId}:
    get:
      description: Retrieves a single task by its identifier
      operationId: getTaskById
      tags:
        - Tasks
      security:
        - openIdConnect:
            - task:read
      parameters:
        - $ref: '#/components/parameters/TaskIdParameter'
        - $ref: '#/components/parameters/VersionParameter'
      responses:
        '200':
          $ref: '#/components/responses/TaskResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/ServiceNotAvailableResponse'
        default:
          $ref: '#/components/responses/DefaultResponse'

    put:
      description: Updates a task with all possible fields
      operationId: updateTaskById
      tags:
        - Tasks
      security:
        - openIdConnect:
            - task:write
      parameters:
        - $ref: '#/components/parameters/TaskIdParameter'
        - $ref: '#/components/parameters/VersionParameter'
      requestBody:
        $ref: '#/components/requestBodies/TaskUpdateRequest'
      responses:
        '200':
          $ref: '#/components/responses/LinkToTaskResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/ServiceNotAvailableResponse'
        default:
          $ref: '#/components/responses/DefaultResponse'

    delete:
      description: Deletes a task
      operationId: deleteTaskById
      tags:
        - Tasks
      security:
        - openIdConnect:
            - task:admin
      parameters:
        - $ref: '#/components/parameters/TaskIdParameter'
        - $ref: '#/components/parameters/VersionParameter'
      responses:
        '204':
          $ref: '#/components/responses/SuccessfulOperationResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/ServiceNotAvailableResponse'
        default:
          $ref: '#/components/responses/DefaultResponse'

  /tasks/{taskId}/status:
    put:
      description: Updates the status of a task
      operationId: updateTaskStatus
      tags:
        - Tasks
        - Task Status
      security:
        - openIdConnect:
            - task:write
      parameters:
        - $ref: '#/components/parameters/TaskIdParameter'
        - $ref: '#/components/parameters/VersionParameter'
      requestBody:
        $ref: '#/components/requestBodies/TaskStatusUpdateRequest'
      responses:
        '200':
          $ref: '#/components/responses/LinkToTaskResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/ServiceNotAvailableResponse'
        default:
          $ref: '#/components/responses/DefaultResponse'

  /tasks/{taskId}/assignees:
    put:
      description: Assigns or updates the assignee of a task
      operationId: updateTaskAssignee
      tags:
        - Tasks
        - Task Assignment
      security:
        - openIdConnect:
            - task:write
      parameters:
        - $ref: '#/components/parameters/TaskIdParameter'
        - $ref: '#/components/parameters/VersionParameter'
      requestBody:
        $ref: '#/components/requestBodies/TaskAssigneeUpdateRequest'
      responses:
        '200':
          $ref: '#/components/responses/LinkToTaskResponse'
        '400':
          $ref: '#/components/responses/BadRequestResponse'
        '403':
          $ref: '#/components/responses/ForbiddenResponse'
        '404':
          $ref: '#/components/responses/NotFoundResponse'
        '500':
          $ref: '#/components/responses/ServiceNotAvailableResponse'
        default:
          $ref: '#/components/responses/DefaultResponse'

components:
  parameters:
    TaskIdParameter:
      name: taskId
      description: Task identifier
      required: true
      in: path
      schema:
        type: string
        format: uuid
        examples:
          - 5dda405a-d28e-490a-8508-1ea3453e91ae

    VersionParameter:
      name: x-version
      description: Version of the API specification used delivered in header
      in: header
      required: true
      schema:
        type: string
        x-extensible-enum:
          - 1.0.0
        default: 1.0.0
        examples:
          - 1.0.0

  responses:
    BadRequestResponse:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    ForbiddenResponse:
      description: Forbidden

    LinkToTaskResponse:
      description: Successful operation - Task created or updated
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Link"

    NotFoundResponse:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    TaskResponse:
      description: Returns a single task
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TaskFull'

    TaskListResponse:
      description: Returns a list of tasks
      content:
        application/json:
          schema:
            type: object
            required:
              - tasks
            properties:
              tasks:
                type: array
                items:
                  $ref: '#/components/schemas/TaskFull'

    ServiceNotAvailableResponse:
      description: Service not available
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    DefaultResponse:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    SuccessfulOperationResponse:
      description: Successful operation

  requestBodies:
    TaskCreationRequest:
      description: Creates a new task
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TaskCreation'

    TaskUpdateRequest:
      description: Updates the task provided
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TaskFull'

    TaskStatusUpdateRequest:
      description: Request to update the status of a task
      content:
        application/json:
          schema:
            type: object
            required:
              - status
            properties:
              status:
                $ref: '#/components/schemas/TaskStatus'

    TaskAssigneeUpdateRequest:
      description: Request to update the assignee of a task
      content:
        application/json:
          schema:
            type: object
            required:
              - employeeId
            properties:
              employeeId:
                type: string
                format: uuid
                description: Employee ID to assign the task to
                examples:
                  - 08a13654-05f3-4664-8c8d-fdd9114ec3be

  schemas:
    Error:
      description: An error object used for error responses
      type: object
      required:
        - title
        - status
        - timestamp
      properties:
        title:
          description: A short description of the problem using kebab-cases
          type: string
          minLength: 2
          maxLength: 255
          examples:
            - task-not-found
            - invalid-status-transition
        detail:
          description: |
            A human-readable description of the problem which can be used by technicians to solve the problem.
          type: string
          examples:
            - The requested task could not be found.
            - Cannot transition from DONE to NEW status.
        timestamp:
          description: Point in time when the error occurred
          type: string
          format: date-time
          examples:
            - 2024-07-01T23:32:54+01:00
        traceparent:
          description: Tracking ID of the API journey
          type: string
          pattern: ^[0-9]{2}-[0-9a-z]{16}-[0-9a-z]{8}-[0-9a-z]{1}[0-9a-z]{1}$
          examples:
            - 00-0af7651916cd43dd8448eb211c80319c-b7ad6b7169203331-01
        severity:
          description: Severity of the according error
          type: string
          enum:
            - FATAL
            - ERROR
            - WARNING
            - INFO
          examples:
            - ERROR

    Link:
      description: Link to an entity
      type: object
      required:
        - type
        - link
      properties:
        type:
          description: Not fully qualified type name of the object
          type: string
          minLength: 2
          maxLength: 155
          examples:
            - Task
        link:
          description: URL to the according entity
          type: string
          format: uri
          examples:
            - https://api.our-company.com/task-management/tasks/74d870fa-9e93-4ffd-907e-038c85e8bc20

    TaskStatus:
      description: Status of a task
      type: string
      enum:
        - NEW
        - IN_PROGRESS
        - DONE
        - REJECTED
      examples:
        - NEW
        - IN_PROGRESS

    TaskCreation:
      description: A new task to be created
      type: object
      required:
        - title
        - dueDate
      properties:
        title:
          description: Title of the task
          type: string
          minLength: 1
          maxLength: 255
          examples:
            - Update API documentation
            - Review pull request #123
        description:
          description: Optional description of the task
          type: string
          minLength: 1
          maxLength: 2048
          examples:
            - Update the OpenAPI specification to include new endpoints
        dueDate:
          description: Due date for the task
          type: string
          format: date
          examples:
            - 2024-12-31
        assigneeId:
          description: Optional employee ID to assign the task to
          type: string
          format: uuid
          examples:
            - 08a13654-05f3-4664-8c8d-fdd9114ec3be

    TaskFull:
      description: A complete task object
      type: object
      required:
        - taskId
        - title
        - status
        - dueDate
        - createdAt
        - updatedAt
      properties:
        taskId:
          description: Unique identifier of the task
          type: string
          format: uuid
          examples:
            - 5dda405a-d28e-490a-8508-1ea3453e91ae
        title:
          description: Title of the task
          type: string
          minLength: 1
          maxLength: 255
          examples:
            - Update API documentation
            - Review pull request #123
        description:
          description: Optional description of the task
          type: string
          minLength: 1
          maxLength: 2048
          examples:
            - Update the OpenAPI specification to include new endpoints
        status:
          $ref: '#/components/schemas/TaskStatus'
        dueDate:
          description: Due date for the task
          type: string
          format: date
          examples:
            - 2024-12-31
        assigneeId:
          description: Employee ID assigned to the task
          type: string
          format: uuid
          examples:
            - 08a13654-05f3-4664-8c8d-fdd9114ec3be
        createdAt:
          description: Timestamp when the task was created
          type: string
          format: date-time
          examples:
            - 2024-07-01T10:30:00+01:00
        updatedAt:
          description: Timestamp when the task was last updated
          type: string
          format: date-time
          examples:
            - 2024-07-02T14:45:00+01:00

  securitySchemes:
    openIdConnect:
      type: openIdConnect
      description: Security scheme for task management
      openIdConnectUrl: "https://idp.our-company.com/configuration"
  
